name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'adopt'
      - uses: gradle/gradle-build-action@v3
        with:
          arguments: deploy
      - name: Upload jorgediazest.indexchecker.portlet jar
        uses: actions/upload-artifact@v4
        with:
          name: index-checker
          path: build/docker/deploy/jorgediazest.indexchecker.portlet*.jar